# Generated by Django 4.2.2 on 2025-05-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('Can_unpublish_product', 'Can_unpublish_product'), ('Can_delete_product', 'Can_delete_product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
